<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Assets\Steam.png" />
      <None Remove="Assets\Games\Game (1).jpg" />
      <None Remove="Assets\Games\Game (1).png" />
      <None Remove="Assets\Games\Game (1).webp" />
      <None Remove="Assets\Games\Game (2).jpg" />
      <None Remove="Assets\Games\Game (2).png" />
      <None Remove="Assets\Games\Game (2).webp" />
      <None Remove="Assets\Games\Game (3).jpg" />
      <None Remove="Assets\Games\Game (3).png" />
      <None Remove="Assets\Games\Game (4).jpg" />
      <None Remove="Assets\Games\Game (4).png" />
      <None Remove="Assets\Games\Game (5).jpg" />
      <None Remove="Assets\Games\Game (5).png" />
      <None Remove="Assets\Games\Game (6).jpg" />
      <None Remove="Assets\Games\Game (6).png" />
      <None Remove="Assets\Games\Game (7).jpg" />
      <None Remove="Assets\Games\Game (7).png" />
      <None Remove="Assets\Games\Game (8).png" />
      <None Remove="Assets\Games\Game (9).png" />
      <None Remove="Assets\Games\Game (10).png" />
      <None Remove="Assets\Games\Game (11).png" />
      <None Remove="Assets\Games\Game (12).png" />
      <None Remove="Assets\Games\Game (13).png" />
      <None Remove="Assets\Games\Game (14).png" />
      <None Remove="Assets\Games\Game (15).png" />
      <None Remove="Assets\Games\Game (16).png" />
      <None Remove="Assets\Games\Game (17).png" />
      <None Remove="Assets\Games\Game (18).png" />
      <None Remove="Assets\Games\Game (19).png" />
      <None Remove="Assets\Games\Game (20).png" />
      <None Remove="Assets\Games\Game (21).png" />
      <None Remove="Assets\Games\Game (22).png" />
      <None Remove="Assets\Games\Game (23).png" />
      <None Remove="Assets\Games\Game (24).png" />
      <None Remove="Assets\Games\Game (25).png" />
      <None Remove="Assets\Games\Game (26).png" />
      <None Remove="Assets\Games\Game (27).png" />
      <None Remove="Assets\Games\Game (28).png" />
      <None Remove="Assets\Games\Game (29).png" />
      <None Remove="Assets\Games\Game (30).png" />
      <None Remove="Assets\Games\Game (31).png" />
      <None Remove="Assets\Games\Game (32).png" />
      <None Remove="Assets\Games\Game (33).png" />
      <None Remove="Assets\Games\Game (34).png" />
      <None Remove="Assets\Games\Game (35).png" />
      <None Remove="Assets\Games\Game (36).png" />
      <None Remove="Assets\Games\Game (37).png" />
      <None Remove="Assets\Games\Game (38).png" />
      <None Remove="Assets\Games\Game (39).png" />
      <None Remove="Assets\Games\Game (40).png" />
      <None Remove="Assets\Games\Game (41).png" />
      <None Remove="Assets\Games\Game (42).png" />
      <None Remove="Assets\Games\Game (43).png" />
      <None Remove="Assets\Games\Game (44).png" />
      <None Remove="Assets\Games\Game (45).png" />
      <None Remove="Assets\Games\Game (46).png" />
      <None Remove="Assets\Games\Test.jpg" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="HandyControl" Version="3.6.0-rc3" />
      <PackageReference Include="WPF-UI" Version="4.0.3" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\Backgrounds\PNG\Launcher.png" />
      <Resource Include="Assets\Backgrounds\PNG\Launcher.png" />
    </ItemGroup>

</Project>
